apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  labels:
    app: logstash
data:
  logstash.conf: |
    input {
      tcp {
        port => 5044
        codec => json
      }
    }

    filter {
      # Aquí puedes agregar filtros según tus necesidades
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "appmanageevents-%{+YYYY.MM.dd}"
      }
    }
