apiVersion: v1
kind: Service
metadata:
  name: appmanageevents-service
spec:
  type: NodePort
  selector:
    app: appmanageevents
  ports:
    - protocol: TCP
      port: 8083  
      targetPort: 8083  
      nodePort: 30007
