CREATE TABLE IF NOT EXISTS salon
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre      VARCHAR(60)                             NOT NULL,
    capacidad   INT,
    descripcion VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_salon PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS evento
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre    VARCHAR(60)                             NOT NULL,
    fecha     DATE,
    invitados INT,
    salon_id  BIGINT,
    CONSTRAINT pk_evento PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS app_user
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(60) NOT NULL,
    password VARCHAR(60) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_roles
(
    user_id BIGINT NOT NULL,
    roles VARCHAR(60) NOT NULL,  -- Cambiar "role" a "roles"
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);

ALTER TABLE evento
    ADD CONSTRAINT FK_EVENTO_ON_SALON FOREIGN KEY (salon_id) REFERENCES salon (id);